Repository playframework/play-samples, pull requests merged in 2023-12, with the labels that each got.

#458 hibernate-core 6.3.2.Final (was 6.3.1.Final)
  play-java-jpa-example/build.sbt
  play-java-rest-api-example/build.sbt
Labels: type:updates

#457 log4j-api, log4j-core, ... 2.22.0 (was 2.21.1)
  play-scala-log4j2-example/build.sbt
Labels: type:updates

#455 play-slick, play-slick-evolutions 5.2.0 (was 5.2.0-RC2)
  play-scala-slick-example/build.sbt
Labels: type:updates

#454 play-ebean, sbt-play-ebean 7.0.0 (was 7.0.0-RC2)
  play-java-ebean-example/project/plugins.sbt
Labels: type:updates

#483 play-java-streaming-example: Add csp nonce
  play-java-streaming-example/app/controllers/HomeController.java
  play-java-streaming-example/app/controllers/HomeController.scala
  play-java-streaming-example/app/controllers/JavaCometController.java
  play-java-streaming-example/app/controllers/JavaEventSourceController.java
  play-java-streaming-example/app/views/index.scala.html
  play-java-streaming-example/app/views/javacomet.scala.html
  play-java-streaming-example/app/views/javaeventsource.scala.html
  play-java-streaming-example/app/views/main.scala.html
  play-java-streaming-example/build.sbt
  play-java-streaming-example/conf/routes
  play-java-streaming-example/public/javascripts/eventsource.js
Labels: status:merge-when-green

#462 Patch updates
  play-java-rest-api-example/build.sbt
Labels: status:merge-when-green, type:updates
