Repository playframework/play-samples, pull requests merged in 2024-07, with the labels that each got.

#724 Update `org.playframework.play` to `v3.1.0-4009e5a0-SNAPSHOT` (was `3.0.*`)
  java/compile-di/gradle/libs.versions.toml
  java/fileupload/gradle/libs.versions.toml
  java/jpa/gradle/libs.versions.toml
  java/rest-api/gradle/libs.versions.toml
  java/streaming/gradle/libs.versions.toml
  java/websocket/gradle/libs.versions.toml
  scala/rest-api/gradle/libs.versions.toml
  scala/streaming/gradle/libs.versions.toml
  scala/websocket/gradle/libs.versions.toml
Labels: type:updates, status:merge-rebase-when-green

#731 [2.9.x] jsoup 1.18.1 (was 1.17.2)
  play-scala-chatroom-example/build.sbt
Labels: type:updates

#727 [3.0.x] h2 2.3.230 (was 2.2.224)
  play-java-ebean-example/build.sbt
  play-java-grpc-example/build.sbt
  play-java-jpa-example/build.sbt
  play-java-rest-api-example/build.sbt
  play-java-starter-example/build.sbt
  play-scala-anorm-example/build.sbt
  play-scala-grpc-example/build.sbt
  play-scala-slick-example/build.sbt
  play-scala-starter-example/build.sbt
Labels: type:updates

#732 [2.9.x] Patch updates
  play-java-akka-cluster-example/project/build.properties
  play-java-chatroom-example/project/build.properties
  play-java-compile-di-example/project/build.properties
  play-java-dagger2-example/project/build.properties
  play-java-ebean-example/project/build.properties
  play-java-fileupload-example/project/build.properties
  play-java-forms-example/project/build.properties
  play-java-grpc-example/project/build.properties
  play-java-hello-world-tutorial/project/build.properties
  play-java-jpa-example/build.sbt
  play-java-jpa-example/project/build.properties
  play-java-rest-api-example/project/build.properties
  play-java-rest-api-example/project/plugins.sbt
  play-java-starter-example/build.sbt
  play-java-starter-example/project/build.properties
  play-java-streaming-example/project/build.properties
  play-java-websocket-example/build.sbt
  play-java-websocket-example/project/build.properties
  play-scala-anorm-example/project/build.properties
  play-scala-chatroom-example/project/build.properties
  play-scala-compile-di-example/project/build.properties
  play-scala-fileupload-example/project/build.properties
  play-scala-forms-example/project/build.properties
  play-scala-grpc-example/project/build.properties
  play-scala-hello-world-tutorial/project/build.properties
  play-scala-isolated-slick-example/project/build.properties
  play-scala-log4j2-example/project/build.properties
  play-scala-macwire-di-example/project/build.properties
  play-scala-rest-api-example/project/build.properties
  play-scala-rest-api-example/project/plugins.sbt
  play-scala-secure-session-example/project/build.properties
  play-scala-slick-example/build.sbt
  play-scala-slick-example/project/build.properties
  play-scala-starter-example/project/build.properties
  play-scala-streaming-example/project/build.properties
  play-scala-tls-example/modules/one/project/build.properties
  play-scala-tls-example/modules/two/project/build.properties
  play-scala-tls-example/project/build.properties
  play-scala-websocket-example/project/build.properties
Labels: status:merge-when-green, type:updates

#729 [3.0.x] Patch updates
  play-java-chatroom-example/project/build.properties
  play-java-compile-di-example/project/build.properties
  play-java-dagger2-example/project/build.properties
  play-java-ebean-example/project/build.properties
  play-java-fileupload-example/project/build.properties
  play-java-forms-example/project/build.properties
  play-java-grpc-example/project/build.properties
  play-java-hello-world-tutorial/project/build.properties
  play-java-jpa-example/build.sbt
  play-java-jpa-example/project/build.properties
  play-java-pekko-cluster-example/project/build.properties
  play-java-rest-api-example/project/build.properties
  play-java-rest-api-example/project/plugins.sbt
  play-java-starter-example/build.sbt
  play-java-starter-example/project/build.properties
  play-java-streaming-example/project/build.properties
  play-java-websocket-example/build.sbt
  play-java-websocket-example/project/build.properties
  play-scala-anorm-example/project/build.properties
  play-scala-chatroom-example/project/build.properties
  play-scala-compile-di-example/project/build.properties
  play-scala-fileupload-example/project/build.properties
  play-scala-forms-example/project/build.properties
  play-scala-grpc-example/project/build.properties
  play-scala-hello-world-tutorial/project/build.properties
  play-scala-isolated-slick-example/project/build.properties
  play-scala-log4j2-example/project/build.properties
  play-scala-macwire-di-example/project/build.properties
  play-scala-rest-api-example/project/build.properties
  play-scala-rest-api-example/project/plugins.sbt
  play-scala-secure-session-example/project/build.properties
  play-scala-slick-example/build.sbt
  play-scala-slick-example/project/build.properties
  play-scala-starter-example/project/build.properties
  play-scala-streaming-example/project/build.properties
  play-scala-tls-example/modules/one/project/build.properties
  play-scala-tls-example/modules/two/project/build.properties
  play-scala-tls-example/project/build.properties
  play-scala-websocket-example/project/build.properties
Labels: status:merge-when-green, type:updates
