Repository playframework/play-samples, pull requests merged in 2024-02, with the labels that each got.

#553 Sample update/play scala isolated slick example
  play-scala-isolated-slick-example/app/controllers/HomeController.scala
  play-scala-isolated-slick-example/app/controllers/UserController.scala
  play-scala-isolated-slick-example/app/models/UserRequest.scala
  play-scala-isolated-slick-example/app/views/create.scala.html
  play-scala-isolated-slick-example/app/views/index.scala.html
  play-scala-isolated-slick-example/app/views/main.scala.html
  play-scala-isolated-slick-example/app/views/update.scala.html
  play-scala-isolated-slick-example/conf/routes
  play-scala-isolated-slick-example/modules/slick/src/main/resources/application.conf
  play-scala-isolated-slick-example/public/stylesheets/main.css
  play-scala-isolated-slick-example/scripts/test-sbt
  play-scala-isolated-slick-example/test/controller/FunctionalSpec.scala
  play-scala-isolated-slick-example/test/controller/MyApplicationFactory.scala
Labels: status:merge-when-green

#539 mockito-core 5.10.0 (was 5.8.0)
  play-java-ebean-example/build.sbt
  play-java-jpa-example/build.sbt
Labels: type:updates

#547 [2.9.x] mockito-core 5.10.0 (was 5.8.0)
  play-java-ebean-example/build.sbt
  play-java-jpa-example/build.sbt
Labels: type:updates

#546 [2.9.x] hibernate-core 6.4.4.Final (was 6.4.1.Final)
  play-java-jpa-example/build.sbt
  play-java-rest-api-example/build.sbt
Labels: type:updates

#538 hibernate-core 6.4.4.Final (was 6.3.2.Final)
  play-java-jpa-example/build.sbt
  play-java-rest-api-example/build.sbt
Labels: type:updates

#543 [2.9.x] sbt-mocha 2.1.0 (was 2.0.1)
  play-java-jpa-example/project/plugins.sbt
Labels: type:updates

#536 sbt-mocha 2.1.0 (was 2.0.1)
  play-java-jpa-example/project/plugins.sbt
Labels: type:updates

#542 [2.9.x] logback-classic 1.5.0 (was 1.4.14)
  play-scala-chatroom-example/build.sbt
Labels: type:updates

#535 logback-classic 1.5.0 (was 1.4.14)
  play-scala-chatroom-example/build.sbt
Labels: type:updates

#545 [2.9.x] gatling-sbt 4.8.1 (was 4.7.0)
  play-java-rest-api-example/project/plugins.sbt
  play-scala-rest-api-example/project/plugins.sbt
Labels: type:updates

#541 Patch updates
  play-java-jpa-example/build.sbt
  play-java-rest-api-example/build.sbt
  play-java-starter-example/build.sbt
  play-java-websocket-example/build.sbt
Labels: status:merge-when-green, type:updates

#549 [2.9.x] Patch updates
  play-java-jpa-example/build.sbt
  play-java-rest-api-example/build.sbt
  play-java-starter-example/build.sbt
  play-java-websocket-example/build.sbt
Labels: status:merge-when-green, type:updates

#555 Enable CI for `main` branch
  .github/workflows/build-test.yml
Labels: status:merge-when-green
