Repository playframework/play-samples, pull requests merged in 2024-06, with the labels that each got.

#650 mockito-core 5.12.0 (was 5.11.0)
  play-java-ebean-example/build.sbt
  play-java-jpa-example/build.sbt
Labels: type:updates

#649 hibernate-core 6.5.2.Final (was 6.4.8.Final)
  play-java-jpa-example/build.sbt
  play-java-rest-api-example/build.sbt
Labels: type:updates

#647 gatling-sbt 4.9.0 (was 4.8.2)
  play-java-rest-api-example/project/plugins.sbt
  play-scala-rest-api-example/project/plugins.sbt
Labels: type:updates

#648 assertj-core 3.26.0 (was 3.25.3)
  play-java-jpa-example/build.sbt
  play-java-starter-example/build.sbt
  play-java-websocket-example/build.sbt
Labels: type:updates

#651 Patch updates
  play-java-chatroom-example/project/plugins.sbt
  play-java-compile-di-example/project/plugins.sbt
  play-java-dagger2-example/project/plugins.sbt
  play-java-ebean-example/project/plugins.sbt
  play-java-fileupload-example/project/plugins.sbt
  play-java-forms-example/project/plugins.sbt
  play-java-grpc-example/project/plugins.sbt
  play-java-hello-world-tutorial/project/plugins.sbt
  play-java-jpa-example/project/plugins.sbt
  play-java-pekko-cluster-example/project/plugins.sbt
  play-java-rest-api-example/project/plugins.sbt
  play-java-starter-example/project/plugins.sbt
  play-java-streaming-example/project/plugins.sbt
  play-java-websocket-example/project/plugins.sbt
  play-scala-anorm-example/project/plugins.sbt
  play-scala-chatroom-example/project/plugins.sbt
  play-scala-compile-di-example/project/plugins.sbt
  play-scala-fileupload-example/project/plugins.sbt
  play-scala-forms-example/project/plugins.sbt
  play-scala-grpc-example/project/plugins.sbt
  play-scala-hello-world-tutorial/project/plugins.sbt
  play-scala-isolated-slick-example/project/plugins.sbt
  play-scala-log4j2-example/project/plugins.sbt
  play-scala-macwire-di-example/project/plugins.sbt
  play-scala-rest-api-example/project/plugins.sbt
  play-scala-secure-session-example/project/plugins.sbt
  play-scala-slick-example/project/plugins.sbt
  play-scala-starter-example/project/plugins.sbt
  play-scala-streaming-example/project/plugins.sbt
  play-scala-tls-example/project/plugins.sbt
  play-scala-websocket-example/project/plugins.sbt
Labels: type:updates

#658 Gradle support for `play-scala-macwire-di-example`
  .github/workflows/build-test.yml
  play-scala-macwire-di-example/.gitattributes
  play-scala-macwire-di-example/.gitignore
  play-scala-macwire-di-example/README.md
  play-scala-macwire-di-example/build.gradle
  play-scala-macwire-di-example/gradle/libs.versions.toml
  play-scala-macwire-di-example/gradle/wrapper/gradle-wrapper.jar
  play-scala-macwire-di-example/gradle/wrapper/gradle-wrapper.properties
  play-scala-macwire-di-example/gradlew
  play-scala-macwire-di-example/gradlew.bat
  play-scala-macwire-di-example/settings.gradle
  test.sh
Labels: status:merge-when-green

#660 Gradle support for `play-scala-starter-example`
  .github/workflows/build-test.yml
  play-scala-starter-example/.gitattributes
  play-scala-starter-example/.gitignore
  play-scala-starter-example/README.md
  play-scala-starter-example/build.gradle
  play-scala-starter-example/gradle/libs.versions.toml
  play-scala-starter-example/gradle/wrapper/gradle-wrapper.jar
  play-scala-starter-example/gradle/wrapper/gradle-wrapper.properties
  play-scala-starter-example/gradlew
  play-scala-starter-example/gradlew.bat
  play-scala-starter-example/settings.gradle
  test.sh
Labels: status:merge-rebase-when-green

#661 Gradle support for `play-scala-streaming-example`
  .github/workflows/build-test.yml
  play-scala-streaming-example/.gitattributes
  play-scala-streaming-example/.gitignore
  play-scala-streaming-example/README.md
  play-scala-streaming-example/app/controllers/HomeController.scala
  play-scala-streaming-example/app/controllers/ScalaCometController.scala
  play-scala-streaming-example/app/controllers/ScalaEventSourceController.scala
  play-scala-streaming-example/app/views/index.scala.html
  play-scala-streaming-example/app/views/main.scala.html
  play-scala-streaming-example/app/views/scalacomet.scala.html
  play-scala-streaming-example/app/views/scalaeventsource.scala.html
  play-scala-streaming-example/build.gradle
  play-scala-streaming-example/build.sbt
  play-scala-streaming-example/gradle/libs.versions.toml
  play-scala-streaming-example/gradle/wrapper/gradle-wrapper.jar
  play-scala-streaming-example/gradle/wrapper/gradle-wrapper.properties
  play-scala-streaming-example/gradlew
  play-scala-streaming-example/gradlew.bat
  play-scala-streaming-example/settings.gradle
  test.sh
Labels: status:merge-rebase-when-green

#662 Fix `play-scala-streaming-example`
  play-scala-streaming-example/app/controllers/HomeController.scala
  play-scala-streaming-example/app/controllers/ScalaCometController.scala
  play-scala-streaming-example/app/controllers/ScalaEventSourceController.scala
  play-scala-streaming-example/app/views/index.scala.html
  play-scala-streaming-example/app/views/main.scala.html
  play-scala-streaming-example/app/views/scalacomet.scala.html
  play-scala-streaming-example/app/views/scalaeventsource.scala.html
  play-scala-streaming-example/build.sbt
Labels: status:merge-rebase-when-green

#679 [3.0.x] Patch updates
  play-java-rest-api-example/build.sbt
Labels: type:updates

#675 [3.0.x] gatling-sbt 4.9.0 (was 4.8.2)
  play-java-rest-api-example/project/plugins.sbt
  play-scala-rest-api-example/project/plugins.sbt
Labels: type:updates

#676 [3.0.x] assertj-core 3.26.0 (was 3.25.3)
  play-java-jpa-example/build.sbt
  play-java-starter-example/build.sbt
  play-java-websocket-example/build.sbt
Labels: type:updates

#678 [3.0.x] play-grpc-generators, ... 0.12.2 (was 0.12.1)
  play-java-grpc-example/project/plugins.sbt
  play-scala-grpc-example/project/plugins.sbt
Labels: type:updates

#682 [2.9.x] assertj-core 3.26.0 (was 3.25.3)
  play-java-jpa-example/build.sbt
  play-java-starter-example/build.sbt
  play-java-websocket-example/build.sbt
Labels: type:updates

#681 [2.9.x] gatling-sbt 4.9.0 (was 4.8.2)
  play-java-rest-api-example/project/plugins.sbt
  play-scala-rest-api-example/project/plugins.sbt
Labels: type:updates

#680 [2.9.x] play-grpc-generators, ... 0.11.1 (was 0.11.0)
  play-java-grpc-example/project/plugins.sbt
  play-scala-grpc-example/project/plugins.sbt
Labels: type:updates

#684 [2.9.x] Patch updates
  play-java-rest-api-example/build.sbt
Labels: status:merge-when-green, type:updates

#708 Revert "Configure Dependabot for Gradle"
  .github/dependabot.yml
Labels: status:merge-when-green

#714 [Gradle] Use ScalaTest + JUnit 5
  scala/chatroom/build.gradle
  scala/chatroom/gradle/libs.versions.toml
  scala/compile-di/build.gradle
  scala/compile-di/gradle/libs.versions.toml
  scala/fileupload/build.gradle
  scala/fileupload/gradle/libs.versions.toml
  scala/forms/build.gradle
  scala/forms/gradle/libs.versions.toml
  scala/hello-world/build.gradle
  scala/hello-world/gradle/libs.versions.toml
  scala/log4j2/build.gradle
  scala/log4j2/gradle/libs.versions.toml
  scala/macwire-di/build.gradle
  scala/macwire-di/gradle/libs.versions.toml
  scala/rest-api/build.gradle
  scala/rest-api/gradle/libs.versions.toml
  scala/secure-session/build.gradle
  scala/secure-session/gradle/libs.versions.toml
  scala/starter/build.gradle
  scala/starter/gradle/libs.versions.toml
  scala/streaming/build.gradle
  scala/streaming/gradle/libs.versions.toml
  scala/websocket/build.gradle
  scala/websocket/gradle/libs.versions.toml
Labels: status:merge-rebase-when-green

#719 Update `org.playframework:play-ebean_*` to `8.3.0` (was `8.0.0-M1`)
  java/ebean/build.gradle.kts
  java/ebean/gradle/libs.versions.toml
Labels: type:updates, status:merge-rebase-when-green
